language: cpp
dist: trusty
sudo: required
matrix:
    include:
        -   os: linux
            env: COMPILER=gcc
            addons:
                apt:
                    sources:
                        -   ubuntu-toolchain-r-test
                    packages:
                        -   g++-6
        -   os: linux
            env: COMPILER=clang
            addons:
                apt:
                    sources:
                        -   llvm-toolchain-trusty-4.0
                    packages:
                        -   clang-4.0
                        -   libc++-dev
script:
    -   mkdir build
    -   cd build
    -   if [ ${COMPILER} = "gcc" ]; then sudo ../.travis/gcc.sh; export CXX=g++; fi
    -   if [ ${COMPILER} = "clang" ]; then sudo ../.travis/clang.sh; export CXX=clang++; export CXXFLAGS=-stdlib=libc++; fi
    -   ../.travis/boost.sh ${COMPILER}
    -   ../.travis/cmake.sh
    -   ./cmake/bin/cmake .. -DCMAKE_BUILD_TYPE=Release -DBOOST_ROOT="$(pwd)/boost/boost_1_64_0" -DBOOST_INCLUDEDIR="$(pwd)/boost/boost_1_64_0" -DBOOST_LIBRARYDIR="$(pwd)/boost/boost_1_64_0/stage/lib"
    -   ./cmake/bin/cmake --build .
    -   ./cmake/bin/ctest -VV
