language: cpp
dist: trusty
sudo: required
env:
    global:
        -   secure: "mmiksQZSGHdf/SqoLgtlYR2PsaR5AlOFot8N9MLlp8N2E5qtVnuVzm7XAPfScrAcswNzUtHLB6coj6eyrPCaPMYAtsUl5pJYZ07B2AiRXVCdvTWq+5nD5sAZ0G5ISuLgdxUkJt4KE8W3rzBT9sw8fhyqxYfS7sJ9b5b6SM3wI/AAZA+OZrRsmhA0GDm2k29TdQgnRONqhcShwj9AIYI8cEHzurjDUNkAiPnXsraFe6bsF1CUXFmaDZbdDxlFuvZ3LkW3dGFBUu7fKIsE2deePpdNFCr2iqNWXTrvhvYMqJthhwl4sI4NofjiiXl3/gd87NOyNvUu4UqoIB4G1znC1Ya5mdD+xslG99hx4B5Ef4fSx5ZKsJBz0TytB9vC/UAMVDSlmisDIlDjYIJv0tNvlHmsKYEfdYXi8sLqQjg1IkoyS/PVCLkEHOeSMzrpecg8Dn6VWLPkjuKcHcFt/FZaSONHF60IpE3r+CypChOtXhbCgrowMvjym65xQ2aPQgk+n8tCJEiBzWxeU2OKbT5y0zHtO0pUaMYkFF4U80KqYOo15IMQ58nQCF/lYJVl17APIg8JJBeD2jHXGHx5kYFaWG50owJfhD1WPbYe6ox4Rq1Pcn77WWmwIyFpuZlebjAz4gEq3BUk8ZGxS/RMz0tbiN3BLpe4IHguBBDfqjG1kOU="
        -   secure: "puwEjThj+gZPimtXkDbtU5SLi7MjNSggWuzE0gHXrqrJou78T24KLlqEkW5x9z9qf3bPEQwrFEFXdx/idRSkWDaXiV2Rcc7hMo5N2bxrmr1nyE5GeN1ite8ceqau26PvT41RhNeXjn/SR5sNgevC77VUMdivf4C86u7KnKR3JkyUCb6nVPGiQDDHu1Z+ZjKpE5VMsvkzs9RCpkO6j+Lx4EKNV7tqF8KaJhJAmyH4QYBJFOrELd/8MAUKv+N+U/P8poG4AyIkN1AgztzNEDvjFK9GojIopYZ8B1xOtNNyCFqwlTYwyQTKzi+uP07ODuJ5HwumdzSyXCpjCOAeKl1eB2Oq0aBA+mSkWVOfyzoA29zz4trDZCJtdrRxMRVcaz/Ip4V5u61BuKWnHkew9/1JvsDOhJe26txFbgOpomBqICksiwhB1xFQYKg8mgufX37OPrlg9qDJtqceOUbWaiq6K78mh2lHoP+3rYlio0pJnaKGmu9o8ifZfCu03ZDA/GIRBthJHwl6cif7QmPGdlOTbJFVhrHRYlhRJldg9+bVsZAeEZuvFDAHYnZThvl7dMIORyWDkIrUea1NAQUzu3ihd+AIDZROwCWfNBUfAHmM2teCZHBjRrsglNYTrRIBrJgF5KmUznyb8Pw6S+Bjwf8UZKVth+3Rtlt7VypEUj1FeDE="
matrix:
    include:
        -   &gcc
            os: linux
            env: COMPILER=gcc BOOST_MINOR=64
            addons:
                apt:
                    sources:
                        -   ubuntu-toolchain-r-test
                    packages:
                        -   g++-6
        -   &clang
            os: linux
            env: COMPILER=clang BOOST_MINOR=64
            addons:
                apt:
                    sources:
                        -   llvm-toolchain-trusty-4.0
                    packages:
                        -   clang-4.0
                        -   libc++-dev
        -   <<: *gcc
            env: COMPILER=gcc BOOST_MINOR=63
        -   <<: *clang
            env: COMPILER=clang BOOST_MINOR=63
        -   <<: *gcc
            env: COMPILER=gcc BOOST_MINOR=62
        -   <<: *clang
            env: COMPILER=clang BOOST_MINOR=62
        -   <<: *gcc
            env: COMPILER=gcc BOOST_MINOR=61
        -   <<: *clang
            env: COMPILER=clang BOOST_MINOR=61
        -   <<: *gcc
            env: COMPILER=gcc BOOST_MINOR=60
        -   <<: *clang
            env: COMPILER=clang BOOST_MINOR=60
        -   <<: *gcc
            env: COMPILER=gcc BOOST_MINOR=59
        -   <<: *clang
            env: COMPILER=clang BOOST_MINOR=59
        -   <<: *gcc
            env: COMPILER=gcc BOOST_MINOR=58
        -   <<: *clang
            env: COMPILER=clang BOOST_MINOR=58
script:
    -   mkdir build
    -   cd build
    -   if [ ${COMPILER} = "gcc" ]; then sudo ../.travis/gcc.sh; export CXX=g++; fi
    -   if [ ${COMPILER} = "clang" ]; then sudo ../.travis/clang.sh; export CXX=clang++; export CXXFLAGS=-stdlib=libc++; fi
    -   ../.travis/boost.sh ${COMPILER} ${BOOST_MINOR}
    -   ../.travis/cmake.sh
    -   ./cmake/bin/cmake .. -DCMAKE_BUILD_TYPE=Release -DBOOST_ROOT="$(pwd)/boost/boost_1_${BOOST_MINOR}_0" -DBOOST_INCLUDEDIR="$(pwd)/boost/boost_1_${BOOST_MINOR}_0" -DBOOST_LIBRARYDIR="$(pwd)/boost/boost_1_${BOOST_MINOR}_0/stage/lib" -DYGGDRASIL_USERNAME="${YGGDRASIL_USERNAME}" -DYGGDRASIL_PASSWORD="${YGGDRASIL_PASSWORD}"
    -   ./cmake/bin/cmake --build .
    -   ./cmake/bin/ctest -VV
    -   ./bin/mcpp_yggdrasil_tests [integration]
