language: cpp
dist: trusty
sudo: required
matrix:
    include:
        -   os: linux
            env: COMPILER=g++-6 COMPILER_FLAGS="-Wall -Wpedantic -Wextra -Werror"
            addons:
                apt:
                    sources:
                        -   ubuntu-toolchain-r-test
                    packages:
                        -   g++-6
                        -   zlib1g-dev
before_install:
    -   export CXX="${COMPILER}"
    -   export CXXFLAGS="${COMPILER_FLAGS}"
script:
    -   mkdir build
    -   cd build
    -   ../.travis/boost.sh
    -   cmake .. -DCMAKE_BUILD_TYPE=Release -DBOOST_ROOT="$(pwd)/boost/boost_1_64_0" -DBOOST_INCLUDEDIR="$(pwd)/boost/boost_1_64_0" -DBOOST_LIBRARYDIR="$(pwd)/boost/boost_1_64_0/stage/lib"
    -   cmake --build .
    -   ctest -VV
